# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-alpha.6


MTA: int
STA: int

def init_apartment(apartment_type: int) -> None:
    ...

def uninit_apartment() -> None:
    ...

class winrt_base:
    ...
